import Link from "next/link";
import { redirect } from "next/navigation";
import { requirePageRole } from "@/server/auth/page-guards";
import { getManagerMetrics, listAuditEvents, listManagerAssets, listManagerUsers } from "@/server/services/manager-service";
import { managerAssetQuerySchema, managerUserQuerySchema } from "@/validation/manager";
import { formatMoney, labelize } from "@/lib/utils";
import { ModerationActionButton } from "@/components/moderation-action-button";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

const mobileCellLabel = "before:mb-1 before:block before:text-[10px] before:font-bold before:uppercase before:tracking-[.12em] before:text-[#7a817f] before:content-[attr(data-label)] sm:before:hidden";
const stackedCell = `block px-4 py-3 ${mobileCellLabel} sm:table-cell`;
const stackedMetaCell = `flex items-center justify-between gap-4 px-4 py-2 ${mobileCellLabel} sm:table-cell sm:py-4`;

function value(params: Record<string, string | string[] | undefined>, key: string) {
  const entry = params[key];
  return Array.isArray(entry) ? entry[0] : entry;
}

export default async function ManagerPage({ searchParams }: { searchParams: SearchParams }) {
  const manager = await requirePageRole("MANAGER").catch(() => null);
  if (!manager) redirect("/dashboard");
  const params = await searchParams;
  const userFilters = managerUserQuerySchema.parse({ search: value(params, "userSearch") || undefined, role: value(params, "role") || undefined, status: value(params, "userStatus") || undefined, page: 1, pageSize: 12 });
  const assetFilters = managerAssetQuerySchema.parse({ search: value(params, "assetSearch") || undefined, status: value(params, "assetStatus") || undefined, category: value(params, "category") || undefined, page: 1, pageSize: 12 });
  const [metrics, users, assets, audit] = await Promise.all([getManagerMetrics(), listManagerUsers(userFilters), listManagerAssets(assetFilters), listAuditEvents()]);

  return <div className="noise min-h-screen"><div className="market-shell max-w-[1400px]">
    <div className="border-b border-[#d6d0c4] pb-5"><p className="eyebrow">Manager operations / trust</p><h1 className="display compact-heading mt-2 text-[#111a22]">Trust console.</h1></div>
    <div className="data-grid mt-6 grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{Object.entries(metrics).map(([key, metric]) => <div key={key} className="data-cell"><p className="stat-label">{labelize(key)}</p><p className="mt-2 text-3xl font-extrabold text-[#111a22]">{metric}</p></div>)}</div>
    <section className="mt-8"><div className="section-kicker mb-4"><div><p className="eyebrow">Participants</p><h2 className="display mt-1 text-3xl tracking-[-.05em] text-[#111a22]">Buyers and sellers</h2></div><form className="flex flex-wrap gap-3"><input name="userSearch" defaultValue={userFilters.search ?? ""} placeholder="Search users" className="focus-ring field-line field-compact" /><select name="role" defaultValue={userFilters.role ?? ""} className="focus-ring field-line field-compact"><option value="">All roles</option><option value="BUYER">Buyer</option><option value="SELLER">Seller</option></select><select name="userStatus" defaultValue={userFilters.status ?? ""} className="focus-ring field-line field-compact"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select><button className="focus-ring action-primary h-11 px-4 text-[10px] font-bold uppercase tracking-[.12em]">Filter</button></form></div><div className="overflow-x-auto border-y border-[#d6d0c4]"><table className="w-full text-left text-sm sm:min-w-[760px]"><thead className="sr-only bg-[#f1ece2] text-[10px] uppercase tracking-[.12em] text-[#737a78] sm:table-header-group"><tr><th className="px-4 py-3">User</th><th>Role</th><th>Status</th><th>Created</th><th className="px-4 text-right">Action</th></tr></thead><tbody className="block divide-y divide-[#d6d0c4] sm:table-row-group">{users.items.map((user) => <tr key={user.id} className="block bg-[#fffefa] py-2 sm:table-row sm:py-0"><td data-label="User" className={stackedCell}><p className="font-bold">{user.displayName}</p><p className="break-words text-xs text-[#737a78]">{user.companyName ?? user.email}</p></td><td data-label="Role" className={stackedMetaCell}>{labelize(user.role)}</td><td data-label="Status" className={stackedMetaCell}><span className={`deal-badge ${user.status === "ACTIVE" ? "status-live" : "status-warning"}`}>{labelize(user.status)}</span></td><td data-label="Created" className={stackedMetaCell}>{new Date(user.createdAt).toLocaleDateString("en-US")}</td><td data-label="Action" className={`${stackedMetaCell} sm:text-right`}>{user.status === "ACTIVE" ? <ModerationActionButton endpoint={`/api/v1/manager/users/${user.id}/status`} payload={{ status: "SUSPENDED" }} label="Suspend" /> : <ModerationActionButton endpoint={`/api/v1/manager/users/${user.id}/status`} payload={{ status: "ACTIVE" }} label="Restore" tone="restore" />}</td></tr>)}</tbody></table></div></section>
    <section className="mt-10"><div className="section-kicker mb-4"><div><p className="eyebrow">Assets</p><h2 className="display mt-1 text-3xl tracking-[-.05em] text-[#111a22]">Marketplace supply</h2></div><form className="flex flex-wrap gap-3"><input name="assetSearch" defaultValue={assetFilters.search ?? ""} placeholder="Search assets" className="focus-ring field-line field-compact" /><select name="assetStatus" defaultValue={assetFilters.status ?? ""} className="focus-ring field-line field-compact"><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option><option value="SUSPENDED">Suspended</option></select><button className="focus-ring action-primary h-11 px-4 text-[10px] font-bold uppercase tracking-[.12em]">Filter</button></form></div><div className="overflow-x-auto border-y border-[#d6d0c4]"><table className="w-full text-left text-sm sm:min-w-[780px]"><thead className="sr-only bg-[#f1ece2] text-[10px] uppercase tracking-[.12em] text-[#737a78] sm:table-header-group"><tr><th className="px-4 py-3">Asset</th><th>Seller</th><th>Status</th><th>Category</th><th className="px-4 text-right">Action</th></tr></thead><tbody className="block divide-y divide-[#d6d0c4] sm:table-row-group">{assets.items.map((asset) => <tr key={asset.id} className="block bg-[#fffefa] py-2 sm:table-row sm:py-0"><td data-label="Asset" className={stackedCell}><Link href={`/assets/${asset.slug}`} className="font-bold hover:text-[#a85834]">{asset.title}</Link><p className="text-xs text-[#737a78]">{asset.country} · {formatMoney(asset.askingPrice, asset.currency)}</p></td><td data-label="Seller" className={stackedMetaCell}>{asset.sellerCompanyName}</td><td data-label="Status" className={stackedMetaCell}><span className={`deal-badge ${asset.status === "PUBLISHED" ? "status-live" : asset.status === "SUSPENDED" ? "status-warning" : ""}`}>{labelize(asset.status)}</span></td><td data-label="Category" className={stackedMetaCell}>{labelize(asset.category)}</td><td data-label="Action" className={`${stackedMetaCell} sm:text-right`}>{asset.status === "SUSPENDED" ? <ModerationActionButton endpoint={`/api/v1/manager/assets/${asset.id}/status`} payload={{ status: "RESTORED" }} label="Restore" tone="restore" /> : <ModerationActionButton endpoint={`/api/v1/manager/assets/${asset.id}/status`} payload={{ status: "SUSPENDED" }} label="Suspend" />}</td></tr>)}</tbody></table></div></section>
    <section className="mt-10"><div className="section-kicker"><p className="eyebrow">Recent audit</p><p className="text-[11px] text-[#737a78]">Latest platform events</p></div><div className="mt-4 divide-y divide-[#d6d0c4] border-y border-[#d6d0c4]">{audit.slice(0, 12).map((event) => <div key={event.id} className="grid gap-2 bg-[#fffefa] px-4 py-3 text-sm md:grid-cols-[170px_1fr_180px]"><span className="font-bold text-[#111a22]">{labelize(event.action)}</span><span className="break-all text-[#485862]">{event.entityType} · {event.entityId}</span><span className="text-xs text-[#737a78]">{new Date(event.createdAt).toLocaleString("en-US")}</span></div>)}</div></section>
  </div></div>;
}
