import Link from "next/link";
import { requirePageRole } from "@/server/auth/page-guards";
import { getSellerAssets } from "@/server/services/asset-service";
import { AssetCard, type AssetCardData } from "@/components/asset-card";
import { AssetLifecycleActions } from "@/components/asset-lifecycle-actions";

export default async function SellerAssetsPage() {
  const user = await requirePageRole("SELLER");
  const assets = await getSellerAssets(user.id);
  return <div className="noise min-h-screen"><div className="fine-grid absolute inset-0 opacity-50" aria-hidden="true" /><div className="market-shell"><div className="flex flex-col justify-between gap-6 border-b border-[#d9d4c9] pb-7 sm:flex-row sm:items-end"><div><p className="eyebrow">Seller studio / inventory</p><h1 className="display compact-heading mt-3">Manage listed assets.</h1><p className="mt-5 max-w-[480px] text-sm leading-6 text-[#50606a]">Prepare listings, keep drafts private, and publish only when the opportunity is ready for the market.</p></div><Link href="/seller/assets/new" className="focus-ring action-primary inline-flex h-11 items-center justify-between px-5 text-[10px] font-bold uppercase tracking-[.14em] sm:w-[170px]">New asset <span className="text-base" aria-hidden="true">↗</span></Link></div>{assets.length === 0 ? <div className="py-20 text-center"><p className="eyebrow">Nothing here yet</p><h2 className="display mt-4 text-4xl tracking-[-.04em]">Start with a draft.</h2><p className="mt-4 text-sm text-[#50606a]">Your first opportunity can stay private until it is ready to be seen.</p></div> : <div className="mt-8 grid gap-4 xl:grid-cols-2">{assets.map((asset) => <div key={asset.id} className="flex flex-col"><AssetCard asset={asset as unknown as AssetCardData} management /><div className="-mt-px border-x border-b border-[#d9d4c9] bg-[#fbfaf6] px-4 py-3"><AssetLifecycleActions id={asset.id} status={asset.status as string} /></div></div>)}</div>}<div className="mt-10 border-t border-[#d9d4c9] pt-5 text-[10px] font-bold uppercase tracking-[.14em] text-[#a1a39b]">{assets.length} {assets.length === 1 ? "asset" : "assets"} in your studio <span className="mx-2">·</span> Seller-only workspace</div></div></div>;
}
